# Imports

In [34]:
import sys
print(sys.executable)
import pandas as pd
import numpy as np
from pathlib import Path

d:\Tisya\projects\AYUSH\venv\Scripts\python.exe

## Loading the data

In [35]:
train_path = Path("../data/raw/FD001/train_FD001.txt")

train_raw = pd.read_csv(train_path, sep=r"\s+", header=None)

print("Shape:", train_raw.shape)
display(train_raw.head())

Shape: (20631, 26)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

## Inspect

In [36]:
print("Rows:", train_raw.shape[0])
print("Columns:", train_raw.shape[1])

Rows: 20631
Columns: 26

In [37]:
print("data types:")
train_raw.dtypes

data types:

0       int64
1       int64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
20    float64
21      int64
22      int64
23    float64
24    float64
25    float64
dtype: object

missing values

In [38]:
print("Total missing values:", train_raw.isna().sum().sum())

Total missing values: 0

In [39]:
print("Sum of all the missing values:")
display(train_raw.isna().sum())

Sum of all the missing values:

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
dtype: int64

In [40]:
print("Number of engines:", train_raw[0].nunique())

Number of engines: 100

In [41]:
engine_cycles = train_raw.groupby(0)[1].agg(["min", "max", "count"])

print("Cycles per engine:")
display(engine_cycles.head(10))
display(engine_cycles.tail(10))

Cycles per engine:

    min  max  count
0
1     1  192    192
2     1  287    287
3     1  179    179
4     1  189    189
5     1  269    269
6     1  188    188
7     1  259    259
8     1  150    150
9     1  201    201
10    1  222    222

     min  max  count
0
91     1  135    135
92     1  341    341
93     1  155    155
94     1  258    258
95     1  283    283
96     1  336    336
97     1  202    202
98     1  156    156
99     1  185    185
100    1  200    200

In [42]:
print("Duplicate rows:", train_raw.duplicated().sum())

Duplicate rows: 0

In [43]:
print("Summary statistics:")
display(train_raw.describe().T)

Summary statistics:

,count,mean,std,min,25%,50%,75%,max
0,20631.0,51.506568,2.922763e+01,1.0000,26.0000,52.0000,77.0000,100.0000
1,20631.0,108.807862,6.888099e+01,1.0000,52.0000,104.0000,156.0000,362.0000
2,20631.0,-0.000009,2.187313e-03,-0.0087,-0.0015,0.0000,0.0015,0.0087
3,20631.0,0.000002,2.930621e-04,-0.0006,-0.0002,0.0000,0.0003,0.0006
4,20631.0,100.000000,0.000000e+00,100.0000,100.0000,100.0000,100.0000,100.0000
5,20631.0,518.670000,0.000000e+00,518.6700,518.6700,518.6700,518.6700,518.6700
6,20631.0,642.680934,5.000533e-01,641.2100,642.3250,642.6400,643.0000,644.5300
7,20631.0,1590.523119,6.131150e+00,1571.0400,1586.2600,1590.1000,1594.3800,1616.9100
8,20631.0,1408.933782,9.000605e+00,1382.2500,1402.3600,1408.0400,1414.5550,1441.4900
9,20631.0,14.620000,5.329200e-15,14.6200,14.6200,14.6200,14.6200,14.6200
10,20631.0,21.609803,1.388985e-03,21.6000,21.6100,21.6100,21.6100,21.6100
11,20631.0,553.367711,8.850923e-01,549.8500,552.8100,553.4400,554.0100,556.0600
12,20631.0,2388.096652,7.098548e-02,2387.9000,2388.0500,2388.0900,2388.1400,2388.5600
13,20631.0,9065.242941,2.208288e+01,9021.7300,9053.1000,9060.6600,9069.4200,9244.5900
14,20631.0,1.300000,0.000000e+00,1.3000,1.3000,1.3000,1.3000,1.3000
15,20631.0,47.541168,2.670874e-01,46.8500,47.3500,47.5100,47.7000,48.5300
16,20631.0,521.413470,7.375534e-01,518.6900,520.9600,521.4800,521.9500,523.3800
17,20631.0,2388.096152,7.191892e-02,2387.8800,2388.0400,2388.0900,2388.1400,2388.5600
18,20631.0,8143.752722,1.907618e+01,8099.9400,8133.2450,8140.5400,8148.3100,8293.7200
19,20631.0,8.442146,3.750504e-02,8.3249,8.4149,8.4389,8.4656,8.5848
20,20631.0,0.030000,3.469531e-18,0.0300,0.0300,0.0300,0.0300,0.0300
21,20631.0,393.210654,1.548763e+00,388.0000,392.0000,393.0000,394.0000,400.0000
22,20631.0,2388.000000,0.000000e+00,2388.0000,2388.0000,2388.0000,2388.0000,2388.0000
23,20631.0,100.000000,0.000000e+00,100.0000,100.0000,100.0000,100.0000,100.0000
24,20631.0,38.816271,1.807464e-01,38.1400,38.7000,38.8300,38.9500,39.4300
25,20631.0,23.289705,1.082509e-01,22.8942,23.2218,23.2979,23.3668,23.6184

In [44]:
constant_columns = train_raw.columns[
    train_raw.nunique() <= 1
]

print("Constant columns:")
print(constant_columns.tolist())

Constant columns:
[4, 5, 9, 14, 20, 22, 23]

## Column Naming and Cleaning

In [45]:
columns = (
    ["unit", "cycle"]
    + [f"op_setting_{i}" for i in range(1, 4)]
    + [f"sensor_{i}" for i in range(1, 22)]
)

print("Number of columns:", len(columns))
print(columns)

Number of columns: 26
['unit', 'cycle', 'op_setting_1', 'op_setting_2', 'op_setting_3', 'sensor_1', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5', 'sensor_6', 'sensor_7', 'sensor_8', 'sensor_9', 'sensor_10', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21']

In [46]:
train = train_raw.copy()
train.columns = columns

display(train.head())
print(train.shape)
print(train.columns.tolist())

,unit,cycle,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

(20631, 26)
['unit', 'cycle', 'op_setting_1', 'op_setting_2', 'op_setting_3', 'sensor_1', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5', 'sensor_6', 'sensor_7', 'sensor_8', 'sensor_9', 'sensor_10', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21']

In [47]:
print(train.dtypes)

unit              int64
cycle             int64
op_setting_1    float64
op_setting_2    float64
op_setting_3    float64
sensor_1        float64
sensor_2        float64
sensor_3        float64
sensor_4        float64
sensor_5        float64
sensor_6        float64
sensor_7        float64
sensor_8        float64
sensor_9        float64
sensor_10       float64
sensor_11       float64
sensor_12       float64
sensor_13       float64
sensor_14       float64
sensor_15       float64
sensor_16       float64
sensor_17         int64
sensor_18         int64
sensor_19       float64
sensor_20       float64
sensor_21       float64
dtype: object

In [48]:
print("Total missing values:", train.isna().sum().sum())
print("Duplicate rows:", train.duplicated().sum())
constant_columns = train.columns[
    train.nunique() <= 1
]

print("Constant columns:")
print(constant_columns.tolist())

Total missing values: 0
Duplicate rows: 0
Constant columns:
['op_setting_3', 'sensor_1', 'sensor_5', 'sensor_10', 'sensor_16', 'sensor_18', 'sensor_19']

In [49]:
train_clean = train.drop(columns=constant_columns).copy()

print("Original shape:", train.shape)
print("Cleaned shape:", train_clean.shape)

display(train_clean.head())

Original shape: (20631, 26)
Cleaned shape: (20631, 19)

,unit,cycle,op_setting_1,op_setting_2,sensor_2,sensor_3,sensor_4,sensor_6,sensor_7,sensor_8,sensor_9,sensor_11,sensor_12,sensor_13,sensor_14,sensor_15,sensor_17,sensor_20,sensor_21
0,1,1,-0.0007,-0.0004,641.82,1589.70,1400.60,21.61,554.36,2388.06,9046.19,47.47,521.66,2388.02,8138.62,8.4195,392,39.06,23.4190
1,1,2,0.0019,-0.0003,642.15,1591.82,1403.14,21.61,553.75,2388.04,9044.07,47.49,522.28,2388.07,8131.49,8.4318,392,39.00,23.4236
2,1,3,-0.0043,0.0003,642.35,1587.99,1404.20,21.61,554.26,2388.08,9052.94,47.27,522.42,2388.03,8133.23,8.4178,390,38.95,23.3442
3,1,4,0.0007,0.0000,642.35,1582.79,1401.87,21.61,554.45,2388.11,9049.48,47.13,522.86,2388.08,8133.83,8.3682,392,38.88,23.3739
4,1,5,-0.0019,-0.0002,642.37,1582.85,1406.22,21.61,554.00,2388.06,9055.15,47.28,522.19,2388.04,8133.80,8.4294,393,38.90,23.4044

In [51]:
train_clean.to_csv('../data/processed/FD001/train_FD001_clean.csv',index=False)

print("Saved: ../data/processed/FD001/train_FD001_clean.csv")

Saved: ../data/processed/FD001/train_FD001_clean.csv