## Imports

In [3]:
import sys
print(sys.executable)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

d:\Tisya\projects\AYUSH\venv\Scripts\python.exe

## Load the data

In [4]:
train_clean = pd.read_csv(
    "../data/processed/FD001/train_FD001_clean.csv"
)

display(train_clean.head())
print(train_clean.shape)

,unit,cycle,op_setting_1,op_setting_2,sensor_2,sensor_3,sensor_4,sensor_6,sensor_7,sensor_8,sensor_9,sensor_11,sensor_12,sensor_13,sensor_14,sensor_15,sensor_17,sensor_20,sensor_21
0,1,1,-0.0007,-0.0004,641.82,1589.70,1400.60,21.61,554.36,2388.06,9046.19,47.47,521.66,2388.02,8138.62,8.4195,392,39.06,23.4190
1,1,2,0.0019,-0.0003,642.15,1591.82,1403.14,21.61,553.75,2388.04,9044.07,47.49,522.28,2388.07,8131.49,8.4318,392,39.00,23.4236
2,1,3,-0.0043,0.0003,642.35,1587.99,1404.20,21.61,554.26,2388.08,9052.94,47.27,522.42,2388.03,8133.23,8.4178,390,38.95,23.3442
3,1,4,0.0007,0.0000,642.35,1582.79,1401.87,21.61,554.45,2388.11,9049.48,47.13,522.86,2388.08,8133.83,8.3682,392,38.88,23.3739
4,1,5,-0.0019,-0.0002,642.37,1582.85,1406.22,21.61,554.00,2388.06,9055.15,47.28,522.19,2388.04,8133.80,8.4294,393,38.90,23.4044

(20631, 19)

## Create RUL

In [5]:
max_cycle = train_clean.groupby("unit")["cycle"].transform("max")

train_clean["RUL"] = max_cycle - train_clean["cycle"]

display(train_clean[["unit", "cycle", "RUL"]].head(10))
print("RUL min:", train_clean["RUL"].min())
print("RUL max:", train_clean["RUL"].max())
print("Missing RUL:", train_clean["RUL"].isna().sum())

   unit  cycle  RUL
0     1      1  191
1     1      2  190
2     1      3  189
3     1      4  188
4     1      5  187
5     1      6  186
6     1      7  185
7     1      8  184
8     1      9  183
9     1     10  182

RUL min: 0
RUL max: 361
Missing RUL: 0

In [7]:
last_cycles = train_clean.loc[
    train_clean.groupby("unit")["cycle"].idxmax(),
    ["unit", "cycle", "RUL"]
]

display(last_cycles.head(10))

print(
    "Engines with final RUL not equal to 0:",
    (last_cycles["RUL"] != 0).sum()
)

      unit  cycle  RUL
191      1    192    0
478      2    287    0
657      3    179    0
846      4    189    0
1115     5    269    0
1303     6    188    0
1562     7    259    0
1712     8    150    0
1913     9    201    0
2135    10    222    0

Engines with final RUL not equal to 0: 0

In [8]:
train_clean.to_csv(
    "../data/processed/FD001/train_FD001_with_rul.csv",
    index=False
)

print("Saved: ../data/processed/FD001/train_FD001_with_rul.csv")

Saved: ../data/processed/FD001/train_FD001_with_rul.csv